FROM ubuntu:groovy

# update dan install openssh
RUN apt-get update && apt-get install -y openssh-server
# membuat direktori sshd
RUN mkdir /var/run/sshd
#set password root
RUN echo 'root:siregar123' | chpasswd
#mengatur permission root login
RUN sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config
#Ssh login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd


ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

#expose port 22 
EXPOSE 22
#membuat otomatis ssh ke container ketika dibuilt
CMD ["/usr/sbin/sshd", "-D"]

